### ISSUE TITLE
More Attractive & Useful 404 Page?

### ISSUE THREAD

**Issue by nelsonic** [FAC-GM/app#133]
The current `404` page is neither informative or helpful: try: http://localhost:8000/invalid
![current-404](https://cloud.githubusercontent.com/assets/194400/11505839/4451df30-9844-11e5-91b6-cd47f0b80781.png)

**Comment by iteles** [comment]
This should also be the case for other errors such as `500` errors - link #131

**Comment by heron2014** [comment]
Example of 404 page. Please share your opinion @iteles, @nelsonic, @SimonLab  
![error](https://cloud.githubusercontent.com/assets/8476884/11510514/fb25fb6c-985b-11e5-8c2d-26928b79b3ad.png)

"/invalid" is any invalid url which user is trying to access.

**Comment by iteles** [comment]
A few notes on this:
+ Really like the 'Take me home' button :+1: 
+ Most users of the app won't be searching for a route, so seeing a route in the error message might still be something they don't understand. For now, it might be worth it to keep it simple with something like 'We couldn't find the page you wanted!' (
+ It would be useful to build a feedback mechanism into these 404/500 fails so that we can capture that something has failed
  + During this MVP stage it makes sense for us to get as much information as possible on what happened, so it would be great to have either a simple button that sends the URL of the page that caused the error (such as in #129) or better yet, a small text box that asks people to let us know what they were doing/searching for/clicking on when they got the error before they send it to us
    + The text for this text box could be something like 'Please help us figure out why by telling us what you were searching for or clicked on that got you here:'
    + It would be pretty impressive if this created an issue on github but we don't need to deal with the authentication issues this might bring up at this stage. Sending an email that we can translate into an issue is enough for now

_Note: The term 'URL' isn't know by everyone outside of the tech world_ :blush:

@nelsonic What do you think?

**Comment by nelsonic** [comment]
@iteles agree that URL is not *common* but fairly certain the people using the app know it.
We could use "address" in the future, but this should be fine for now. :+1:

**Comment by iteles** [comment]
@nelsonic I didn't explain that very well, sorry! I was hoping for your thoughts on incorporating a feedback mechanism into the 404 page 😊 (may be too 'involved')

**Comment by heron2014** [comment]
Resolved by #162
