### ISSUE TITLE
Picture profile

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#136]
As a user I want to see a "ghost picture" if a picture fails to load as I want to have a consistent design across the application.
![pictureprofile](https://cloud.githubusercontent.com/assets/6057298/11509818/4ae9f77e-9858-11e5-80b9-85c283c53669.png)
![pictureprofile2](https://cloud.githubusercontent.com/assets/6057298/11509817/4ae8717e-9858-11e5-955b-bd7b8caa0512.png)

**Comment by nelsonic** [comment]
we are going to see this 404 error on the client regardless of wether we show a default profile picture or not because the CDN will fail to return a valid picture...
We would need to issue a periodic request for every CDN object to ensure that all the images are still valid.

also, could we use a different image as the *default*? 
https://www.google.co.uk/search?q=default+profile+picture&tbm=isch

**Comment by heron2014** [comment]
Resolved by added ghost picture of the client logo.
