### ISSUE TITLE
Template Engine

### ISSUE THREAD

**Issue by abdiahmed** [FAC-GM/app#14]
Have you considered using a template engine?

**Comment by heron2014** [comment]
We are using Vision - templates rendering support for hapijs [L7](https://github.com/FAC-GM/app/blob/c95fe53c0157ca7247281da9b1d3e62621568f21/lib/index.js#L7). Do you have anything specific on your mind?

**Comment by abdiahmed** [comment]
I was expecting something along the lines of Jade or EJS.

**Comment by heron2014** [comment]
We are using handlebars :smile:

**Comment by heron2014** [comment]
Thanks @abdiahmed for suggestion. I will check out what Jade does, we are using Handlebars at the moment .

**Comment by nelsonic** [comment]
@abdiahmed do yo have a *specific* reason for preferring Jade or EJS...?

**Comment by abdiahmed** [comment]
@nelsonic no particular preference, they're just the ones that I am familiar with.

**Comment by nelsonic** [comment]
Do you prefer the *syntax* of EJS or the (*perceived*) elegance of Jade?
+ EJS: `Hello <%= name %>!` 
+ Jade: `Hello #{name}!`
+ Handlebars: `Hello {{name}}!` 

*seems* like there *because* there are more (*different*) characters to type in EJS there is more scope for `input/syntax error` ... would you not agree...?
Oh and hold on, Jade uses a *hash* symbol for to denote a variable substitution... aren't those *also* used for CSS IDs...? Surely that's obvious to everyone, right? Sadly, no. Oh you forgot the *hash* in front of your curly brace? 

![jade syntax error](http://img1.wikia.nocookie.net/__cb20121108215300/life-after-people-fanon/images/5/5e/Exploding_Computer.jpg)

I did a comparative study on this a while back, and while Jade *looks* "nice" *initially* its a *nightmare* to debug on anything beyond a micro-app and is un-friendly to designers who try to edit your templates once you have rolled off the project. (*do you* ***want*** *to get phone calls when things "break" 3 months after you* ***thought*** *you had finished working on a project...?*)

As much as I *love* trying new things, sometimes the Boringly *Simple* is Best. (*unless you're hoping for job security... in which case use [***ECT***](http://ectjs.com/) which has the "*highest performance*" but nobody at your client will know it so they will keep calling you when they need to change things...

*Conclusion*: **Handlebars** for ***client work***. 
**Handlebars** has a more *beginner-friendly syntax* (*closer to html*) thus *shallower learning curve*
for people joining/taking over your project.

**Note**: I *highly encourage everyone* to use what ever else they want to try for *personal projects*, and when you have a *demonstrable* benefit to end-users to switch to the new+shiny (*react-ify-wow-tastic-latest-and-greatest*) then write a *readme* on it and share it with everyone.

**Comment by abdiahmed** [comment]
@nelsonic great comparison, I agree on jade - one extra tab and it breaks. I haven't tried handle bars, but will definitely give it a go.

**Comment by SimonLab** [comment]
@abdiahmed thanks for the question, at the moment we are using Handlebars. Do you think you can close this issue?
