### ISSUE TITLE
Investigate nock 

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#253]
After implementing test for sending_emails with expired_token [here](https://github.com/FAC-GM/app/blob/email/test/sendemailHelper.test.js)we came across of this error: 

![failed_test](https://cloud.githubusercontent.com/assets/8476884/13056478/7caea28c-d40d-11e5-8be5-1e0d1643f7f0.png)

**Comment by nelsonic** [comment]
@heron2014 this is because `nock` is configured to intercept a request to `https://www.googleapiis.com...` so it then tries to mock all subsequent requests...
I could not figure out how to turn it *off*... so I ended up putting all my mock tests at the *end*...
see: https://github.com/nelsonic/sendemail-gmail/blob/dcb11a154f2605d63ec8a707e13801f72755d265/test/z_mock_oauth_flow.test.js

**Comment by heron2014** [comment]
thanks @nelsonic. I am running mocks at the end and it now works.

**Comment by nelsonic** [comment]
:+1:
