### ISSUE TITLE
Viewing activity of a candidate

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#382]
We are already display the initials of a user if a profile is a first degree connection of this user. Instead of tracking the activity with the first degree initials we suggest to create a new property/tags to know who see the LI of a candidate, like this we keep the two feature separated:

**Comment by heron2014** [comment]
Basic UI proposed for this feature: 

![initials](https://cloud.githubusercontent.com/assets/8476884/14172813/11885096-f732-11e5-8858-91ea50b5fd8a.png)

@iteles @Adam-JF what do you think?

**Comment by heron2014** [comment]
This is how currently we display following: 

- The number '1' next to email indicator is informing the user about:  how many users viewed this profile on LI

![viewedby-number](https://cloud.githubusercontent.com/assets/8476884/14346769/91236a92-fcab-11e5-9a02-7811f269719a.png)

- The 'AC 2' means that I have viewed this profile on LI 2 times.

![viewedby-initials-times](https://cloud.githubusercontent.com/assets/8476884/14346792/b2d8e37e-fcab-11e5-8abd-e3fb586fe84d.png)

@iteles @Adam-JF please let me know what you think.

**Comment by iteles** [comment]
@heron2014 I think that on the individual profile it needs to say "Viewed on LinkedIn by:" before showing the initials but looks good!
@adam-jf?

**Comment by heron2014** [comment]
@iteles that's true!! I will update it!

**Comment by heron2014** [comment]
Updated version (detailed candidate view):

![viewed-by-detailed](https://cloud.githubusercontent.com/assets/8476884/14348201/dd9a99f2-fcb2-11e5-80cd-189549679ea0.png)

If nobody viewed this profile, the section Viewed By won't be shown.

@Adam-JF feel free to search for different icon if this one is not suitable. 

@iteles @Adam-JF what do you think?

**Comment by Adam-JF** [comment]
I like it 👌

**Comment by heron2014** [comment]
[api.js](https://github.com/FAC-GM/app/blob/activity-viewedBy/lib/api.js) is the endpoint where we get data from ext

We have a following scenarios: 
-**first scenario**
Url (from ext) exist in ES [L20-L33](https://github.com/FAC-GM/app/blob/activity-viewedBy/lib/api.js#L20-L33) and is a first degree connection we allow to update the whole profile 

Check if **viewedBy** property is already in a profile otherwise set to empty array - [L73](https://github.com/FAC-GM/app/blob/activity-viewedBy/lib/api.js#L73). 
The viewedBy property has been created using this helper [add_viewedBy_candidate](https://github.com/FAC-GM/data-copy/blob/master/helpers/add_viewedBy_candidate.js)
Although I opened the issue [1](https://github.com/FAC-GM/data-copy/issues/1) and because of that I set the condition to empty array [L73](https://github.com/FAC-GM/app/blob/activity-viewedBy/lib/api.js#L73) in case doesn’t exist.

From ext - (request.payload.viewedBy) which is a string with the userName [L75](https://github.com/FAC-GM/app/blob/activity-viewedBy/lib/api.js#L75), based on that string we are able to match the userName from ext with a user name (linkedinName)[L16](https://github.com/FAC-GM/app/blob/activity-viewedBy/lib/database-helpers/elasticsearch/get_user_by_li_name.js#L16) in ES [get_user_by_li_name](https://github.com/FAC-GM/app/blob/activity-viewedBy/lib/database-helpers/elasticsearch/get_user_by_li_name.js), if there is a match we get user object with the id.

Also we have created another helper to add property linkedinName to users [add_user_li_property](https://github.com/FAC-GM/data-copy/blob/master/helpers/add_user_li_property.js)

We are creating new userObj based on userName from ext with id, fullname, initials [L77-L81](https://github.com/FAC-GM/app/blob/activity-viewedBy/lib/api.js#L77-L81) to be able to pass it to relevant profile.

Now we are able to check if user.id exist in viewedBy array [L82](https://github.com/FAC-GM/app/blob/activity-viewedBy/lib/api.js#L82), by creating new filtered array called userNameExist.

If userNameExist is empty that means we don't have that user in viewedBy array, so we push the userObj to viewedBy array with the new timestamp to keep track.

If the userNameExist is not empty, that means we already have userObj in viewedBy so we can push new timestamp to keep on track if someone second time viewed the profile. 
[L87-L92](https://github.com/FAC-GM/app/blob/activity-viewedBy/lib/api.js#L87-L92)

Update the viewedBy property with all the above condition [L94](https://github.com/FAC-GM/app/blob/activity-viewedBy/lib/api.js#L94)

Added viewedBy property to [L22](https://github.com/FAC-GM/app/blob/activity-viewedBy/lib/helpers/complete_profile.js#L22)

-**second scenario**
Not a first degree connection , we have to repeat all the above [L116-L131](https://github.com/FAC-GM/app/blob/activity-viewedBy/lib/api.js#L116-L131) but this time we only update the viewedBy property in ES [L133-L140](https://github.com/FAC-GM/app/blob/activity-viewedBy/lib/api.js#L133-L140)

-**third scenario**
If we have the url but we couldn't find it in ES , we are doing all of the above and we are creating the profile [L153-L170](https://github.com/FAC-GM/app/blob/activity-viewedBy/lib/api.js#L153-L170)

-**fourth scenario**
If we didn’t received the url from ext , we just saving the profile in ES [L181-L205](https://github.com/FAC-GM/app/blob/activity-viewedBy/lib/api.js#L181-L205)

**Comment by heron2014** [comment]
Why ES can't match the user object. We compare name which is defined (comes from ext), in particular with Ines and with names.linkedinName from ES; I logged the DB and on Ines we have :linkedinName

![real-db-mapping](https://cloud.githubusercontent.com/assets/8476884/14385095/9275b77e-fd96-11e5-8bca-de9b37cbd781.png)

see line [L16](https://github.com/FAC-GM/app/blob/activity-viewedBy/lib/database-helpers/elasticsearch/get_user_by_li_name.js#L16)

and we get this error:
![issue-mapping](https://cloud.githubusercontent.com/assets/8476884/14384992/0bbc9266-fd96-11e5-9217-62051658f32c.png)

While matching me for example has no issue:
![no-issue-mapping](https://cloud.githubusercontent.com/assets/8476884/14385146/d148c3e2-fd96-11e5-92be-2829a168a98b.png)


@nelsonic if you have a moment to see why is this happening? Thank you in advance.

**Comment by heron2014** [comment]
Investigating 'match_phrase' in ES.

**Comment by heron2014** [comment]
Why match as opposed to match_phrase query worked matching name from ext with our DB?

**match** - according to the ES book (page 104) says : 
'The **match** query should be the standard query that you reach for whenever you want
to query for a full-text'. 

**match_phrase** - is used to match the phrase, the words in the query phrase must all appear and also they must be in the same position to find the match.

To be honest it is a bit confusing why match_phrase couldn't match successfully. My first thought was because; name from ext had an accent and in our db under linkedinName key - Ines is without accent - that's why it failed to match. But when we did a test and changed name without accent in Linkedin we still had the same problem, which as theory says should match. 

As a result we use match because it is a standard query on full-text that ES recommends. 

But I am still very curious in regards why match_phrase fails. :open_mouth:

**Comment by heron2014** [comment]
The interesting thing is that when I use my localhost database and try to get initials from LI logged in as Ines I still have trouble, but this time completely different - is related to mapping:

![error-mapping-localhost](https://cloud.githubusercontent.com/assets/8476884/14423248/bbca775c-ffd2-11e5-838c-e7ba773df410.png)

While running it on real database there is no problem. 

Is our data format (mapping) on viewedBy key is different than on real database?

**Comment by heron2014** [comment]
What is **mapping** and how it can impact queries is explained [here](https://github.com/learnTrack/Q-A/issues/63).

**Comment by heron2014** [comment]
```js
curl -XGET 'localhost:9200 or url to real db/index/type/_mapping?pretty' 
```

above command will detailed all data formats for each field. 
Official docs - [mapping-type](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html#mapping-type) says:

"Each mapping type contains a list of fields or properties pertinent to that type. A user type might contain title, name, and age fields, while a blogpost type might contain title, body, user_id and created fields. **Fields with the same name in different mapping types in the same index must have the same mapping.** "

It looks like we have **id** field mapped as two different data type: sometimes is a 'string' and sometimes is a 'long'.

More about field-conflicts [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html#field-conflicts)

**Comment by heron2014** [comment]
Worth reading [elasticsearch-nested-mapping-and-filter](http://joelabrahamsson.com/elasticsearch-nested-mapping-and-filter/)

**Comment by heron2014** [comment]
@Adam-JF would it be possible for you to prepare us a list of all the users with their current fullname on Li and LIR? (to confirm what we have already ).Please send us on email, thank you.

**Comment by Adam-JF** [comment]
Working great.
