### ISSUE TITLE
Restructed status for candidate

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#421]
As a consultant I would like to see the current status of the relevant candidate. The status should have information such as: 
- who is the client 
- what job vacancy
- current stage 
- initials of the consultant/owner

On top of that I would like to add additional status to the same candidate and be able to delete the status. 

Basic wireframe for this feature:

![status](https://cloud.githubusercontent.com/assets/6057298/14916939/4df09478-0e14-11e6-9a5b-b249c694f812.png)

**Comment by iteles** [comment]
@heron2014 
The first 2 screens look great - worth noting that the request from @Adam-JF is that the first drop-down limits the options that appear in the second one and then the Stages are hard-coded for now.

Some thoughts:
+ The 3rd screen doesn't look right but I think that's because here it looks like a big input box which isn't the case - I like how you're displaying the owners though!
+ The delete button doesn't need to take up so much screen real estate - I would make it a simple chunky **x** for now in mid-grey
+ We're missing the edit option (pencil)

**Comment by SimonLab** [comment]
Thanks for the feedbacks. For the edit button, is it simpler to  delete the status and then create a new one?

**Comment by iteles** [comment]
Yes and no. from a coding perspective, certainly simpler. But from a user's perspective it doesn't make much sense to have to delete a status and create a new one to advance a candidate to the next stage of the same job...

**Comment by heron2014** [comment]
Hi @Adam-JF , could you please list all the stages for the status feature, thanks.

**Comment by Adam-JF** [comment]
Submitted
Phone Screen
Interview Stage 1
Interview Stage 2
Interview Stage 3
Technical Test
Face to Face
Offer
Placement

**Comment by heron2014** [comment]
Current status of the candidate can be edited by tapping the edit button. This possibility is missing from the above wireframes.

**Comment by heron2014** [comment]
TO DO: 
* [ ] transform userId into initials 
* [ ] UI 
* [ ] add statusCurrent and statusHistory into all candidates

**Comment by SimonLab** [comment]
@Adam-JF The status feature is online.

**Comment by Adam-JF** [comment]
Working great.
