### ISSUE TITLE
csv upload questions

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#497]
@Adam-JF we have a few questions concerning this feature.

- "upload an Excel or CSV file into the app", It's easier for us to work with csv file, instead of having to create a parser specifically for the Excel format could you convert the file manually?

- "This will then match with candidates in the app", The elasticsearch database has by default a limit on how many searches you can execute, do you have an idea of the number of candidates you could have on the csv file?

- "That list needs to rank and filter people by adding requirements". Is adding a skills search field (like on the home page) your idea?

- "We would like the ability to download that list" - What kind of information you want to download (fullname, location, company,...) and in which format you want the file downloaded to be?

- " re-upload an excel/csv file and for it only to import new names without creating duplicates." Could you add the new profiles to the current csv file and re upload this file? It will reset the file and search again for candidates matching the csv list.

Let us know if you have more details about these features it will help us to better estimate the work.

**Comment by heron2014** [comment]
Basic wireframes how we see this feature: 

![csv-upload](https://cloud.githubusercontent.com/assets/8476884/16114995/3e3b3bd2-33bc-11e6-8145-df86776b501b.png)

![send-email](https://cloud.githubusercontent.com/assets/8476884/16114976/24b60b06-33bc-11e6-823c-9074144a39fa.png)

**Comment by Adam-JF** [comment]
It's easier for us to work with csv file, instead of having to create a parser specifically for the Excel format could you convert the file manually? - 
**Yes, I can easily convert an Excel file to CSV for the uploads if this makes the process easier - Campaign Monitor does allow you to download the details in various formats include csv**

The elasticsearch database has by default a limit on how many searches you can execute, do you have an idea of the number of candidates you could have on the csv file? 
**The csv files will vary dependent on the success of the marketing campaign - at the moment we can expect to be creating useful lists including between 50 and about 600 names/emails. What is the limit on the number of searches we can do? Would a palatable alternative be to upload files with a maximum number of names on, but several times, so I would split the upload.**

Is adding a skills search field (like on the home page) your idea? 
**The way I see it is that it's similar functionality to what already exists for the main search features we have in the app. However, as opposed to searching for skills in the entire database of 130,000 names + we're merely doing a dedicated skills search but within that list of X number of names. The idea was the result of the meeting between myself, Alex and Nick, there isn't specific ownership but it's required if we're to ensure our emails are as relevant and as targeted as possible, this ultimately is the goal of the feature**

What kind of information you want to download (fullname, location, company,...) and in which format you want the file downloaded to be? 
**The information required for Campaign Monitor is simply the person's name and email address - however, the more information downloaded the better - as such I think it would be good to include the person's full name, email address, location, company and job title. The accepted file formats for Campaign Monitor are Excel documents (e.g. .xls, .xlsx, .csv), comma separated value text files (.csv), tab delimited text files (.txt), vCard files and compressed file formats (for example: .zip, .rar, .7z). Any of these are acceptable but if we want to keep things consistent, let's shoot for csv unless one of the ones mentioned above is simpler.**

Could you add the new profiles to the current csv file and re upload this file? It will reset the file and search again for candidates matching the csv list. 
**There are functions I can perform on Excel which will remove duplicates from a list I upload, however this isn't fool proof - what would happen if I upload a csv file with a duplicate name on it, would the app put two profiles up in the same name? Similarly, I assume if I were re-uploading a file in its entirety, this would take longer than perhaps adding what amounts to an additional 20 names or so. One of the requirements from Nick and Alex was that the app recognised a duplicate from the file upload and as a result did not upload it if the person's name was already present on a list. Also, if we were to action a campaign and as a result we had 200 people we wanted to create a list with, imagine then that the following week I send a new campaign to the same demographic but now have 300 people engaging with it, including some of the original 200 people, naturally it's likely I would have lost some of the original 200 people (they may not have read it yet, didn't see the email etc.) in spite of the fact they were engaged with the marketing the first time and may be interested, I wouldn't want to lose those people already on the list just because they didn't see the follow up email**

Also, another requirement is that the lists on each page are fixed when going through them, occasioanlly on the app if someone does a search, as they're searching through pages, the results change on the page and the order of the profiles changes and occasionally we have people appearing on one page and then another, in spite of the fact there isn't a duplicate profile, they seem to jump from time to time.

**Comment by SimonLab** [comment]
Thanks for the details.

Just to be sure, the only way we can find candidates on the app from the csv file is by their email as it is a unique string. Searching by name might get some wrong profiles. From I understand you will be able to get the emails from Campaign Monitor, is that right?

"each page are fixed" - Do you refer to the order of the list of candidates and how they are displayed on the page? If so how do you want the candidates to be ordered?

On the current app a candidate can appeared on the next page because the number of candidates has changed (new profiles have been added during the search).

**Comment by Adam-JF** [comment]
Yes, we can download the email addresses as well as the names from Campaign Monitor.

I refer to the order - arranging them alphabetically seems like the most sensible way to do it.

The app does occasionally move profiles, we've tested this even when no one is using LinkedIn/the extension.

**Comment by Adam-JF** [comment]
What would happen if someone who isn't in the app is uploaded?

Is it possible that this could create a blank profile with simply their name and email address?

This would involve also being able to add a LinkedIn address manually to their profile to later populate the information.

**Comment by SimonLab** [comment]
We could create an empty profile for each emails that couldn't be match with an existing candidate. To add the LI url we will need to create a form and an ajax call to update the value like on the info section. We estimate this work to be 1 day developer

**Comment by SimonLab** [comment]
@Adam-JF could you send us an example of the csv format, we need to know how to target the emails values. At the moment we are working on a version of a csv file where a column "email" is defined, would this work for you?

**Comment by heron2014** [comment]
This issue has been resolved.
