### ISSUE TITLE
csv Upload Problem

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#552]
Attempting to upload a csv file with both name and email columns defined with circa 250 emails on it.

Getting the following: 

![screen shot 2016-07-15 at 15 59 42](https://cloud.githubusercontent.com/assets/15364186/16878651/50aa0dfc-4aa5-11e6-9d58-a3cf614bbb35.png)

**Comment by heron2014** [comment]
@Adam-JF Could you please send me the file that you have tried to upload and cause this above error, thank you

**Comment by Adam-JF** [comment]
@heron2014 Sent it over to you :)

**Comment by heron2014** [comment]
Thanks @Adam-JF

**Comment by heron2014** [comment]
@Adam-JF I can see where the problem is. The way we parse the csv files into the app is that the columns must be in certain order. This file starts from Name and should start from Email. I have changed the order and it works as expected. 

So the order should be:
![email-name](https://cloud.githubusercontent.com/assets/8476884/16911858/d4e8701a-4cd8-11e6-979d-ad6e529a26b8.png)

And then the list appears in the app:
![assurance](https://cloud.githubusercontent.com/assets/8476884/16911865/def5ae42-4cd8-11e6-8fab-5695ce52906a.png)

**Comment by heron2014** [comment]
@Adam-JF Please test this and update this issue, thank you

**Comment by Adam-JF** [comment]
@heron2014 Tried this and it still isn't working. Received the same error message as before.

**Comment by heron2014** [comment]
@Adam-JF thanks Adam, I will do more tests.

**Comment by heron2014** [comment]
@Adam-JF could you please test upload this file on staging area. Let me know how it went.

**Comment by Adam-JF** [comment]
@heron2014 Fixed 👍

**Comment by Adam-JF** [comment]
@heron2014 Thank you for sorting this :)
