### ISSUE TITLE
Highlight Keywords in Search Results 

### ISSUE THREAD

**Issue by nelsonic** [FAC-GM/app#68]
As a person searching for words I want to see those words highlighted in the text of the search results so it makes the text easier/faster to scan and I can get the information I need to get on with my work.

<hr />
@iteles I *estimate* it will take me **6h** to get the *initial version* of this done. 
Please let me know if I'm ok to get started *or* if there is another priority for today. 
thanks.

**Comment by iteles** [comment]
:+1: :blush: 

No other priorities for _today_ - our main priorities are currently things we have agreed to pair on and will start working on _tomorrow_.

**Comment by nelsonic** [comment]
Done the "*easy*" part of building the module: https://github.com/dwyl/search-result-keyword-highlighter/pull/3

Next:
+ export the method for use in the browser? or do highlighting on the server...?

**Comment by SimonLab** [comment]
We were using the highlight function to all the html content. But this is not the right solution as it hightlight also the html tags and not only the content. We need to apply the hightlight function only to the content and to do this we need to call multiple time the function.

**Comment by SimonLab** [comment]
After some investigation to apply the highlight with handlebars, unfortunately it's seems not as easy as it looked:
- we don't want to apply the highlight to all the html because some html tags will be broken
- we don't want to apply the highlight on the data of the objects because we will need to use {{{ }}} from handlebars which can allow some xss

Our new approach is to produce the highlight on the front end:
- define a class for each elements where we want to apply the highlight
- For each elements with this class: 
   - check if the content contain the keywords we are searching for
   - if yes add a new class ('highlight'). This class is used in css to apply specific styling

This solution won't work if javascript is disable on the browser but this functionality doesn't break anything else if it's not working!

**Comment by nelsonic** [comment]
Agreed. there is a way around this we discussed. Let me know if you have any questions implementing it.

**Comment by nelsonic** [comment]
This feature was merged in #108

**Comment by iteles** [comment]
Will be revisited in technical task #111
