### ISSUE TITLE
User permissions

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#86]
As an owner of the application I want _only the people who have the right permissions_ to access the application as I don't want people unknown to me to access our private pages.

**Comment by nelsonic** [comment]
A permissions system *might* take **1h** to *scope*...

**Comment by iteles** [comment]
@SimonLab Could you please check the time label on this and change to actual time taken (if different to the original estimate) and confirm this issue can be closed with the merging of PR #88?

**Comment by SimonLab** [comment]
Testing the permission take us more time than I thought as I was trying to mock the environment variable. At the end **it took us 2h**. @iteles I'd like to keep the initial time estimation label as it can be nice to track which tasks take longer to complete. Should we create a label for "time taken"

**Comment by iteles** [comment]
@SimonLab As we discussed verbally this morning, changing the label means that the last thing tracked in the issue is the change from Time Estimated to Time Taken. Shall we try this method for this sprint (rather than going back to retrofit 'time taken' labels to our closed issues) and then trial an extra label if we feel the need to next sprint? :blush:
